### ISSUE TITLE
could you tell me how to deal with it ?

### ISSUE THREAD

**Issue by qikong333** [ievgennaida/animation-timeline-control#10]
![image](https://user-images.githubusercontent.com/23370805/82137277-3ce69380-9849-11ea-8eb0-f242f0aad1eb.png)

angular  version：8.0.0

**Comment by ievgennaida** [comment]
Hello,  this error is saying that the interface is expected and you are not passing all the required properties. 

For example, snapsPerSeconds is required.

Anyway, in the new version >2.0.7, all those fields are optional.
Please use the latest version.
