### ISSUE TITLE
Could you tell me how to set and get this time??

### ISSUE THREAD

**Issue by qikong333** [ievgennaida/animation-timeline-control#12]
![image](https://user-images.githubusercontent.com/23370805/82782350-b1938080-9e8e-11ea-9dea-f21a070cbfe9.png)

**Comment by ievgennaida** [comment]
You can see the list of public methods here:
https://github.com/ievgennaida/animation-timeline-control/blob/master/lib/timeline.d.ts
or 
https://github.com/ievgennaida/animation-timeline-control/blob/master/src/timeline.ts

All available methods will be displayed in the popup if you are using IDE like visual studio code. 

To set time units you can use: 
```
timeline.setTime(4000);
timeline.redraw();
```

To get current time you can use:
```
timeline.getTime();
```

Or you can subscribe on time changed event:

TypeScript:
```
timeline.onTimeChanged((event: TimelineTimeChangedEvent) => {
  if(event.source !== TimelineEventSource.User){
  // Do something.
  }
});
```
