### ISSUE TITLE
help me !

### ISSUE THREAD

**Issue by chenguzhen87** [ievgennaida/animation-timeline-control#15]
I want to do similar video online editing, how to render an image to canvas? How to cut video? Very urgent

**Comment by ievgennaida** [comment]
This question is too broad and not related to the component. 
It's not possible to give in two words how everything should work. 
In general you might need backend with the ffmpeg editor 


You can try stackoverflow  or projects that are solving exactly this problem:

**Comment by chenguzhen87** [comment]
@ievgennaida ,thanks,maybe try https://github.com/daem-on/fwf

**Comment by chenguzhen87** [comment]
@ievgennaida 
![image](https://user-images.githubusercontent.com/28331609/100978170-fb1b0180-357c-11eb-935e-71940ae0ce3e.png)
My English is not very good, can not express very well, I want to be based on the animation timeline control library, to reality, in the browser can clip video operation, of course, the real video clip in the background, with ffmpeg library implementation, the above screenshot is the bibibi implementation interface, the timeline can display pictures, can also cut pictures, now encountered problems, how to in animation timeline control Draw up, cut and move pictures up and down

**Comment by ievgennaida** [comment]
This control does not have a feature to show images on a canvas. 
You should create your own implementation. You can use draw image method:
https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/drawImage
I can guess this is not easy task while you have to decompose image flow and show series of images. 
The link I have shared also does not have this feature.

**Comment by chenguzhen87** [comment]
@ievgennaida ,Thanks for your reply
