### ISSUE TITLE
Implementing without Angular, just HTML or React

### ISSUE THREAD

**Issue by crushingCodes** [ievgennaida/animation-timeline-control#20]
Hi, I love your demo, you have done a great job. Im just wondering what you mean by no dependancy. Is it possible to use this without Angular? I am currently using React, but if it works in HTML I should be able to port it accross fairly easy. No pressure to implement or anything, just curious

**Comment by crushingCodes** [comment]
Actually problem solved, I noticed your demo was the html version, so i just copied your setup for that and it works in html.

**Comment by ievgennaida** [comment]
@crushingCodes good :) 
Yes, it was tested in pure HTML and additionally in Angular.
'no dependency' means that external dependencies are not used during the execution. 
all dependencies used are used only to build the package.

Please feel free to provide react import example to be a bit clearer in the Readme file.

**Comment by crushingCodes** [comment]
@ievgennaida Sure, Ill try to make a react example pr in this repo, I dont know how pretty its going to be since I have never really made a component ready for export, but Ill have a go

**Comment by ievgennaida** [comment]
@crushingCodes  I was more about small import read me example, but it's up to you :)

**Comment by crushingCodes** [comment]
@ievgennaida Thanks, I needed to do a few workarounds to make React happy. Not sure if you have used react but the way everything renders is a bit different to Angular,. The good news is I was able to directly import your library without any internal changes.

Please see https://github.com/ievgennaida/animation-timeline-control/pull/21 for implementation
