### ISSUE TITLE
showing images in the canvas keyframe 

### ISSUE THREAD

**Issue by khanzzirfan** [ievgennaida/animation-timeline-control#23]
Hi , This is a fantastic useful library. 
I wonder if it is possible to add images to the timeline as below ? please help with one simple example

![image](https://user-images.githubusercontent.com/8625166/147731357-542b47c0-09a5-4d79-8eff-a11fe29d33d2.png)

**Comment by ievgennaida** [comment]
Hello @khanzzirfan, 
Unfortunately I have no much time to support this component at the moment. 

I would imagine that canvas drawImage can be used during the row renderer call (See _renderRows from timeline.ts).
Images can be passed as a collection or rendered using some kind of call back to override and extend render row function (can be part of the options as an example),
To avoid flickering images should be persistent during the render function call (should be created and added to the collection outside of renderer execution). On image loaded even component 'redraw' can be called.

P.s. I have updated dev dependencies so debugger works again and also last row has different height to match picture above.

**Comment by khanzzirfan** [comment]
Hi @ievgennaida  Thanks for the reply.  I just re-created same code using react-konva/ konvajs library, A basic version of yours library. This is really helpful now.  Here is sandbox if someone wants to have look at  it. 
https://codesandbox.io/s/videoscrubber-react-konva-y4yjm
