### ISSUE TITLE
setTime does not visually refresh timeline.

### ISSUE THREAD

**Issue by 5Mixer** [ievgennaida/animation-timeline-control#3]
Calling `timeline.setTime` adjusts the timeline time, however does not redraw the canvas. Some other event, such a mouse drag, is required to show changed time.

Furthermore, calling `timeline.redraw` fails with ```requestAnimationFrame' called on an object that does not implement interface Window.```

Thanks for releasing this timeline component as open-source!

Edit: I see you're calling `redraw` after `setTime` in your animator project. This may be related to the context of my function calls. I am calling `setTime` and `redraw` in a Vue watch function. On a breakpoint at the requestAnimationFrame, `window` seems fine and `this` is the timeline object.

**Comment by 5Mixer** [comment]
Resolved. It was indeed a context issue. To redraw, I call
```this.timeline.redraw.call(self)```

By passing in Self, the window object is properly accessed and requestAnimationFrame works. I believe this has something to do with the opening of `index.js`, but as the issue only seems apparent in my Vue project, I'll close.

**Comment by ievgennaida** [comment]
The project is migrated to the TS with multiple fixes. 
This problem also should be resolved.
