### ISSUE TITLE
Timeline units display

### ISSUE THREAD

**Issue by PlkMarudny** [ievgennaida/animation-timeline-control#34]
There is a way to change the way timeline units are displayed:
```
timeline._formatUnitsText = ...
```

but is there a way to control how many units are displayed? They start overlapping if there is a lot of them to be displayed - in case there  is a very long timeline zoomed out to fill the whole container.

**Comment by ievgennaida** [comment]
@PlkMarudny Text length suppose to be automatically determined to avoid overlapping. Could you please send a format use are using and a screenshot?

**Comment by PlkMarudny** [comment]
Actually, it seems to be fine, sorry for the false alarm.
