### ISSUE TITLE
Why we have slow (unwanted) rerender on setTime()?

### ISSUE THREAD

**Issue by Maksclub** [ievgennaida/animation-timeline-control#36]
Please, could you explain why when calling setTime() within an RxJs stream (values are emitted rapidly due to requestAnimationFrame), there is a significant performance hit with a long rerender of all elements, whereas with drag, the time change happens at the same speed, but there is no noticeable rerendering?

![ezgif-4-e082334972](https://github.com/ievgennaida/animation-timeline-control/assets/11223987/5c7225e8-cb4d-4493-b2d3-a1b2c58437a8)

```
   this.replayComposer.currentTime$
      .subscribe(t => {
        if (!this.timeline) {
          return
        }

        const isSet = this.timeline.setTime(t);
        if (isSet) {
          this.timeline.redraw();
        }
      })
```

**Comment by ievgennaida** [comment]
@Maksclub maybe rxjs is called it too often?
To ensure that this is a root cause, you can remove all other redraw calls.

RxJs has a denounce method, please try use and see whether issued Is gone
```
this.replayComposer.currentTime$.pipe(
    debounceTime(200),
  )
      .subscribe(t => {
        if (!this.timeline) {
          return
        }

        const isSet = this.timeline.setTime(t);
        if (isSet) {
          this.timeline.redraw();
        }
      })
```

**Comment by Maksclub** [comment]
Pipe timers (with setTimeout, setInterval) is very slowly then it is not variant for me. If I make debounce without timers I see rerender all elements while when dragging the timeliner, only it is redrawn

**Comment by Maksclub** [comment]
Solution
```
  this.replayComposer.currentTime$
      .pipe(filter(() => !!this.timeline))
      .subscribe((t) => {
        // @ts-ignore
        this.timeline._setTimeInternal(t)
        // @ts-ignore
        this.timeline.redraw()
      })
```

Result:

![ezgif-1-6d1af9fb6d](https://github.com/ievgennaida/animation-timeline-control/assets/11223987/36a669da-88aa-4b61-84b8-4931f1151b1b)
