### ISSUE TITLE
Capitalization of lib files leads to errors in build on Linux

### ISSUE THREAD

**Issue by CHuesser** [ievgennaida/animation-timeline-control#45]
Modules are not found while building on Linux due to capitalization. 

E.G.:
 - lib/settings/styles/**T**imelineRowStyle.d.ts vs './settings/styles/**t**imelineRowStyle'
 - lib/utils/**T**imelineElement.d.ts vs './utils/**t**imelineElement'
 etc.

**Comment by ievgennaida** [comment]
@CHuesser should be fixed in the latest version. 2.3.2

To get the capitalization fix applied you might need to remove the lib on drive and install it again.
