### ISSUE TITLE
Is it possible to display a gauge on the body of the timeline?

### ISSUE THREAD

**Issue by antennix** [ievgennaida/animation-timeline-control#46]
In the screenshot, you can see a vertical dashed gauge extending over the header and body of the timeline.

![image](https://github.com/ievgennaida/animation-timeline-control/assets/16828930/2dd46dc6-ef7d-4dc6-8d41-d765e1aaa14c)

However, there is no body gauge in the demo, and I don't think there is an option to display this gauge.
https://ievgennaida.github.io/animation-timeline-control/

Is there a better way to display this gauge?

**Comment by ievgennaida** [comment]
You mean whether it's possible to draw a vertical dotted line?

**Comment by antennix** [comment]
that's right.

**Comment by ievgennaida** [comment]
As I remember, there is no configurable way, you have to override a function to draw it.
