### ISSUE TITLE
Feature Request: Options to help using the timeline for music-related applications

### ISSUE THREAD

**Issue by aaronsantiago** [ievgennaida/animation-timeline-control#49]
Currently there are a couple features that would help using the timeline for music:

- The "denominators" for the tick marks between numbers is hardcoded to a very non-musical 1, 2, 5, 10. Exposing this via configuration would help dramatically--for music or for dance 1, 2, 4, 8 etc. would be preferred. https://github.com/ievgennaida/animation-timeline-control/blob/5e4bb08573e96f82d218a9d834f3e90f5d7aa99e/src/utils/timelineUtils.ts#L4
- The numbers above the timeline are treated as if they are always seconds, making things confusing when treating the timeline in terms of beats, as they additionally get converted into minutes/hours as the timeline grows. Adding a callback to replace `_formatUnitsText` dynamically would be optimal, as I could then implement "numbers only" display, or counting to 8s, etc. https://github.com/ievgennaida/animation-timeline-control/blob/5e4bb08573e96f82d218a9d834f3e90f5d7aa99e/src/timeline.ts#L1493

**Comment by ievgennaida** [comment]
@aaronsantiago
1. Denominators I can make configuble, but cannot do this week.
2. format units -> you can just override existing function.

**Comment by ievgennaida** [comment]
@aaronsantiago Do you have any mock-up or reference with the expected outcome (overall)?
